import '../App.css';

function Djete({aa, bb}) {
  return (
    <div>
        <table className="tablica">
        <tr>
          <td><b>Od:</b></td>
          <td><b>Do:</b></td>
          <td><b>Datum:</b></td>
          <td><b>Vrijeme:</b></td>
          <td><b>Zrakoplov:</b></td>
        </tr>
        <tr>
          <td>Split</td>
          <td>London</td>
          <td>11.01.2022</td>
          <td>6:00</td>
          <td>{aa.ime}</td>
        </tr>
        <tr>
          <td>Zagreb</td>
          <td>Frankfurt</td>
          <td>12.08.2021</td>
          <td>13:00</td>
          <td>{bb.ime}</td>
        </tr>
        <tr>
          <td>Split</td>
          <td>Pariz</td>
          <td>4.12.2021</td>
          <td>16:10</td>
          <td>{aa.ime}</td>
        </tr>
        <tr>
          <td>Zagreb</td>
          <td>Edinburg</td>
          <td>5.08.2021</td>
          <td>17:30</td>
          <td>{bb.ime}</td>
        </tr>
        <tr>
          <td>London</td>
          <td>Split</td>
          <td>13.08.2021</td>
          <td>11:00</td>
          <td>{bb.ime}</td>
        </tr>
        <tr>
          <td>Dubrovnik</td>
          <td>Dubai</td>
          <td>27.03.2022</td>
          <td>7:00</td>
          <td>{bb.ime}</td>
        </tr>
        <tr>
          <td>Dubai</td>
          <td>Split</td>
          <td>3.03.2022</td>
          <td>14:30</td>
          <td>{bb.ime}</td>
        </tr>
        <tr>
          <td>Zagreb</td>
          <td>Cairo</td>
          <td>12.12.2021</td>
          <td>13:15</td>
          <td>{aa.ime}</td>
        </tr>
        <tr>
          <td>Zagreb</td>
          <td>New York</td>
          <td>13.08.2021</td>
          <td>6:45</td>
          <td>{aa.ime}</td>
        </tr>
        <tr>
          <td>Split</td>
          <td>Prag</td>
          <td>23.02.2022</td>
          <td>15:30</td>
          <td>{bb.ime}</td>
        </tr>
        <tr>
          <td>Zadar</td>
          <td>Oslo</td>
          <td>23.07.2021</td>
          <td>10:20</td>
          <td>{aa.ime}</td>
        </tr>
        <tr>
          <td>Zagreb</td>
          <td>Barcelona</td>
          <td>4.04.2022</td>
          <td>9:15</td>
          <td>{aa.ime}</td>
        </tr>
        <tr>
          <td>London</td>
          <td>Rijeka</td>
          <td>22.09</td>
          <td>11:30</td>
          <td>{bb.ime}</td>
        </tr>
        <tr>
          <td>Madrid</td>
          <td>London</td>
          <td>18.05.2021</td>
          <td>10:30</td>
          <td>Airbus A319CJ</td>
        </tr>
        <tr>
          <td>Lisabon</td>
          <td>Zadar</td>
          <td>12.07.2021</td>
          <td>7:00</td>
          <td>Arbus A319CJ</td>
        </tr>
        <tr>
          <td>Helsinki</td>
          <td>Moskva</td>
          <td>13.02.2022</td>
          <td>22:00</td>
          <td>{bb.ime}</td>
        </tr>
        <tr>
          <td>Ljubljana</td>
          <td>Budimpešta</td>
          <td>14.02.2022</td>
          <td>19:30</td>
          <td>Airbus A319CJ</td>
        </tr>
        <tr>
          <td>Berlin</td>
          <td>Split</td>
          <td>11.06.2021</td>
          <td>11:00</td>
          <td>{aa.ime}</td>
        </tr>
        <tr>
          <td>Zagreb</td>
          <td>Atena</td>
          <td>11.01.2022</td>
          <td>6:00</td>
          <td>{bb.ime}</td>
        </tr>
      </table>
    </div>
  );
}

export default Djete;
